### ISSUE TITLE
Type 'MonikProto.Event' does not conform to protocol 'GeneratedMessageProtocol'

### ISSUE THREAD

**Issue by anatoliykant** [Totopolis/monik.ios#1]
I have several protobuf files which are actively used in a project with some other languages, and now need swift versions. I can build .pb.swift files successfully but when I add them to Xcode, I am receiving tons of bugs mainly composed of:

Type 'MonikProto.Event' does not conform to protocol 'GeneratedMessageProtocol'
I use the Protobuf (3.3.0) & ProtocolBuffers-Swift (3.0.22).
What could be the problem?

**Comment by idalidchik** [comment]
It looks that protocol GeneratedMessageProtocol has changed, new methods are required to be implemented in MonikProto.Event etc. Quick fix is to comment new methods:

public protocol GeneratedMessageProtocol: ProtocolBuffersMessage {
    //FIXME: associatedtype BuilderType: GeneratedMessageBuilderProtocol
    static func parseFrom(data: Data) throws -> Self
    static func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> Self
    static func parseFrom(inputStream:InputStream) throws -> Self
    static func parseFrom(inputStream:InputStream, extensionRegistry:ExtensionRegistry) throws -> Self
    static func parseFrom(codedInputStream:CodedInputStream) throws -> Self
    static func parseFrom(codedInputStream:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Self
    //FIXME: subscript(key: String) -> Any? { get }
}
